### ISSUE TITLE
"gaiatest: error: no such option: --log-xunit" error 

### ISSUE THREAD

**Issue by stephendonner** [mozilla/marketplace-tests-gaia#101]
I kicked off a run of http://jenkins1.qa.scl3.mozilla.com/view/Marketplace/job/flame-kk-319.mozilla-b2g32_v2_0.nightly.ui.marketplace/236/console, and got the following error:

16:31:16 + gaiatest --testvars=/home/webqa/webqa-credentials/b2g/common.json --testvars=/home/webqa/webqa-credentials/b2g/b2g-25.2.json --address=localhost:2829 --device=814fcec9 --log-xunit=results/results.xml --timeout=60000 --log-html=results/index.html --restart marketplacetests/tests/manifest.ini --type=b2g
16:31:17 Usage: gaiatest [options] test_file_or_dir <test_file_or_dir> ...
16:31:17 
16:31:17 gaiatest: error: no such option: --log-xunit

ping @davehunt @bobsilverberg @silne30 et al

**Comment by jonallengriffin** [comment]
On B2G 2.0, the relevant option was called --xml-output

You'll probably run into the same problem with --log-html; it should likely be --html-output

**Comment by stephendonner** [comment]
Both Dave + Bob are out tomorrow for holiday -- @geoelectric - able to take a look/help?  Thx!

**Comment by davehunt** [comment]
I've fixed the jobs and triggered new builds. This was caused by a global change to using mozlog for HTML and XUnit reports, which is not supported on v2.0. Sorry about that.

Dave Hunt

**Comment by stephendonner** [comment]
:+1:

**Comment by bobsilverberg** [comment]
@davehunt It looks like this issue can be closed. Do you agree?

**Comment by davehunt** [comment]
Yep. Done.
