### ISSUE TITLE
test_marketplace_search_and_install_app.TestSearchMarketplaceAndInstallApp shouldn't be checking for Developer Name

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests-gaia#127]
Looks like test_marketplace_search_and_install_app.TestSearchMarketplaceAndInstallApp checks that the dev name is "Fake App Developer". This is incorrect since the developer name is selected from a bunch of options and there is no guarantee that it will always be the same. Let us remove that check for now. Thanks!

**Comment by davehunt** [comment]
This project is no longer being maintained.
