### ISSUE TITLE
[Payment flow][zippy] Check that entering an incorrrect PIN throws an error message

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests-gaia#24]
## Pre-conditions
1. Test app being used is available @ https://marketplace-dev.allizom.org/app/test-zippy-with-me?src=all-reviewed
2. The account already has a PIN associated with it

## Steps to test
1. Launch marketplace-dev
2. Search for the app "Test Zippy With Me"
3. Click on the app to load the details page
4. Click on the purchase button
5. Log in using valid Persona credentials (Please use a brand new persona account every time if possible)
6. In the Enter PIN screen, enter an incorrect PIN

## Expected results
1. Marketplace-dev launches without any issues
2. Search returns the app being searched for
3. Details page for the selected app loads
4. Webpay loads in a trustedUI and user is prompted to log in using Persona.
5. Log in using Persona is successful
6. Upon entering an incorrect PIN, There is a user message which says "Wrong PIN" and is in red.

**Comment by AndreiH** [comment]
I'll start working on this

**Comment by bobsilverberg** [comment]
This was addressed by PR #93
