### ISSUE TITLE
[Payment flow][zippy] Check the 'Forgot your PIN' flow

### ISSUE THREAD

**Issue by krupa** [mozilla/marketplace-tests-gaia#25]
## Pre-conditions
1. Test app being used is available @ https://marketplace-dev.allizom.org/app/test-zippy-with-me?src=all-reviewed
2. The account already has a PIN associated with it

## Steps to test
1. Launch marketplace-dev
2. Search for the app "Test Zippy With Me"
3. Click on the app to load the details page
4. Click on the purchase button
5. Log in using valid Persona credentials (Please use a brand new persona account every time if possible)
6. In the Enter PIN screen, click on the 'Forgot your PIN?' link
7. In the 'Forgot your PIN' screen, click 'Reset'
8. Log in using Persona 
9. In the Reset PIN screen, enter new PIN value; Click Continue
10. Confirm the new PIN

## Expected results
1. Marketplace-dev launches without any issues
2. Search returns the app being searched for
3. Details page for the selected app loads
4. Webpay loads in a trustedUI and user is prompted to log in using Persona.
5. Log in using Persona is successful
6. The Forgot PIN screen loads with a Cancel and Reset buttons
7. Log in to persona is successful and the Reset PIN screen loads
8. Reset PIN screen loads with the Continue button disabled. Enter the 4 PIN digits enabled the Continue button
9. Confirm the same PIN again; Click continue. There is a success message which says "Pin reset"

7. Clicking the 'Reset' button, loads the persona flow

**Comment by viorelaioia** [comment]
I opened PR #73

**Comment by bobsilverberg** [comment]
This was addressed by PR #94
