### ISSUE TITLE
Project needs Refactoring

### ISSUE THREAD

**Issue by AndreiH** [mozilla/marketplace-tests-gaia#59]
As new coverage is added/needs to be added to this project we need to refactor the tests/page objects in folders to be more cleaner/tidy. It would be more easier to add new coverage as the project grows. (for contributors also).
Eg. Create and move tests in category subfolders (test_payments, test_reviews, test_search) also for page objects. 
We should also rename files from <code>test_marketplace_feedback_login.py</code> to just simply <code>test_feedback_login.py</code> as this is no longer part of the big project gaia.

**Comment by davehunt** [comment]
This project is no longer being maintained.
