### ISSUE TITLE
Fix test_marketplace_search_and_install_app to uninstall app first

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests-gaia#69]
When I run `test_marketplace_search_and_install_app` repeatedly locally, it fails after the first run because the app is already installed. We have code in many of our tests that checks if the app in question is installed and then uninstalls it before proceeding with the test. We should add similar code into `test_marketplace_search_and_install_app` to address this issue.

**Comment by bobsilverberg** [comment]
What is we choose the app first (using the existing logic), and save the name in a variable, then uninstall it, then proceed with the test? That would work, wouldn't it?

**Comment by AndreiH** [comment]
Good point! I updated the PR, and it's working great

**Comment by bobsilverberg** [comment]
This landed in https://github.com/mozilla/marketplace-tests-gaia/commit/c7674b2c96f77dac341c8960e8e3f347e511445d
