### ISSUE TITLE
Running setup.py does not install dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla/marketplace-tests-gaia#82]
Running `python setup.py install` should install all dependent packages from `requirements.txt`.

**Comment by bobsilverberg** [comment]
I was unable to get that working originally, as I was pointing to a GitHub repo and not PyPI. Now that we are using FxAPom from PyPI we can resolve that. In fact, we likely no longer need `requirements.txt` at all and can just add FxAPom as a dependency in `setup.py`.

**Comment by bobsilverberg** [comment]
This was fixed in #91
