### ISSUE TITLE
Sometimes the keyboard pops up during login, which causes login to fail

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests-gaia#86]
This is something I have noticed while trying to debug some failures.

During the login sequence, when the password is being typed into the password box, sometimes this causes the keyboard to appear, and then, shortly thereafter, disappear. It seems that the keyboard pops at the same time that marionette is trying to tap on the "Sign In" button which causes it to fail.

There are a couple of issues here:
1. The keyboard is getting in the way of the button. Why is it appearing, and why only sometimes, and what can we do about that.
2. That tap on the button is not successful, but marionette doesn't recognize this. No error is thrown. The code believes that the button has been tapped and continues merrily along, but the button has not in fact been tapped.

@davehunt Do you have any thoughts on these issues?

**Comment by davehunt** [comment]
I have seen an issue when signing in where the keyboard is not dismissed. I can see why this might cause Marionette to fail to click an element that's partially obstructed by the keyboard, but I don't believe we need to dismiss the keyboard. It most likely pops up as a response to interactions on the input boxes.

I replicated the issue 2/5 times, but not once I applied the following patch:

```patch
diff --git a/marketplacetests/firefox_accounts/app.py b/marketplacetests/firefox_accounts/app.py
index 8082084..9e1e518 100644
--- a/marketplacetests/firefox_accounts/app.py
+++ b/marketplacetests/firefox_accounts/app.py
@@ -2,7 +2,8 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-from marionette.by import By
+from marionette import expected, By, Wait
+
 from gaiatest.apps.base import Base
 
 
@@ -59,10 +60,11 @@ class FirefoxAccounts(Base):
         self.marionette.find_element(*self._next_button_locator).tap()
 
     def tap_sign_in(self):
-        self.keyboard.dismiss()
-        self.switch_to_correct_login_frame()
-        self.wait_for_element_displayed(*self._sign_in_button_locator)
-        self.marionette.find_element(*self._sign_in_button_locator).tap()
+        sign_in = Wait(self.marionette).until(
+            expected.element_present(*self._sign_in_button_locator))
+        Wait(self.marionette).until(expected.element_displayed(sign_in))
+        # Bug 937053 - tap() method should calculate elementInView from the coordinates of the tap
+        self.marionette.execute_script('arguments[0].scrollIntoView(false);', [sign_in])
+        sign_in.tap()
 
     @property
     def is_not_you_logout_link_visible(self):
```

**Comment by bobsilverberg** [comment]
@davehunt's suggestion fixed this issue.
