### ISSUE TITLE
Can no longer tap on the region select box in the debug screen of marketplace-dev

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests-gaia#87]
We are seeing failures with an inability to select a region from the debug screen, which is required for some tests.

After some investigation I have found that when we try to tap on the select box, nothing happens. I tried step debugging and was able to reproduce this. Calling either `tap()` or `click()` on that element returns `True`, but nothing happens. The tap and click are not recognized by the UI. I then tried using `send_keys` and that seemed to work, but seems strange.

I will open a PR which uses `send_keys` which should fix the failure, but this deserves more investigation. I am also concerned that this is another example of what I discussed in issue #86, where marionette fails to tap on an element, but doesn't realize that.

[1] https://github.com/mozilla/marketplace-tests-gaia/blob/master/marketplacetests/marketplace/regions/debug.py#L24

**Comment by bobsilverberg** [comment]
@mstriemer Do you have any idea if this might be caused by changes in https://github.com/mozilla/fireplace/commit/a4ef033960f3ba9c7658b5536fb829b6128f59ac, and if so whether we need to do something different from tapping on the `<select>`?

**Comment by mstriemer** [comment]
The `id` of the `<select>` changed. It still has `name="region"` so I'd suggest using that. The new id is `debug-region` so you could use that but there's no reason to change the name so I'd try that one.

In https://github.com/mozilla/marketplace-tests-gaia/blob/master/marketplacetests/marketplace/regions/debug.py#L14:
```py
_region_select_locator = (By.NAME, 'region')

**Comment by mstriemer** [comment]
I opened #90 with the fix.

**Comment by bobsilverberg** [comment]
Thanks @mstriemer. As I commented on PR #90, the issue with not being able to tap on the element isn't because of the locator change. I had already changed the locator when I found the "unable to tap" issue. Do you know if there is anything else about the code that changed for the debug screen that might have caused this inability to tap?

**Comment by mstriemer** [comment]
Weird. My knowledge of selenium is pretty limited so I'm not sure how it tries to tap things. I don't see anything covering the element so it seems like it should work. There is one event handler there but it shouldn't trigger until after a selection is made.

**Comment by davehunt** [comment]
My guess is that a change pushed the target element down the page just enough to trigger [bug 937053](https://bugzilla.mozilla.org/show_bug.cgi?id=937053), which landed after the v2.0 branch was created. I talk about this more here: https://github.com/mozilla/marketplace-tests-gaia/pull/88#discussion_r26674500

**Comment by bobsilverberg** [comment]
This has been resolved via a workaround.
