### ISSUE TITLE
Remove unnecesary steps from payment tests, and possibly refactor

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests-gaia#96]
@davehunt noted in [a comment] (https://github.com/mozilla/marketplace-tests-gaia/pull/93#discussion_r27211314) that when running the payment tests we don't need to go to the app details screen before installing, we could simply click install from the search results page. We should look into removing that extra step.

It might also be worth creating some helper methods that encapsulate commonly used workflows, such as all the steps that get us to the "Create pin" screen, or maybe even all the steps that take us to the "Buy / Cancel" screen, as that flow us used in multiple tests, and it's unneccesary to maintain multiple copies of that same code.

**Comment by tarun1992** [comment]
Can I take this task?

**Comment by bobsilverberg** [comment]
I am working on this as part of changes being made to use the first found paid app, as opposed to a specific app.

**Comment by davehunt** [comment]
This project is no longer being maintained.
